### ISSUE TITLE
Release-Checklist

### ISSUE THREAD

**Issue by Paspartout** [Okabintaro/UntitledDuckMod#49]
- [x] Make new Markdown description for Modrinth
  - [x] Mention the duck dance feature
- [x] Update github readme
- [ ] Make new Photos with iris after #31
- [ ] Maybe even make small trailer with the replay mod
